### ISSUE TITLE
Fonts are not loading on several pages

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#1]
List of pages with font not loading:
- `aboutus.do`
- `contactus.do`
- `privacypolicy.do`
- `terms.do`
- `legalInformatiion.do`
- `policyForms.do`
- `financialRatings.do`
- `blood.do`
- `life-help.do`
- `life-need.do`
- `life-afford.do`

Font error message in console:
- `Typekit: the domain "devweb01.eastus.cloudapp.azure.com" isn't in the list of published domains for kit "qns3hng".`

**Comment by mohankumarac12** [comment]
Fixed the typekit font issue.
