### ISSUE TITLE
Annual Income field not hidden

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#11]
The **Annual Income** field should be hidden on `mainQuote.do` if coming from ALL paths except **Help Me Determine My Coverage**.

- If coming from `life-need.do` or `&src=iknowwhatiwant`, the quote form should:
  - Hide the Annual Income field
  - Hide the Monthly Premium field
  - Show the Coverage field and populate the dropdown with the amount selected
- If coming from `life-afford.do`, the quote form should:
  - Hide the Annual Income field
  - Hide the Coverage field
  - Show the Premium Amount field and populate the dropdown with the amount selected
- If coming from `&src=affordability`, the quote form should:
  - Hide the Annual Income field
  - Hide the Coverage field
  - Show the Premium Amount field and populate the dropdown with $25
- If coming from `life-help.do`, the quote form should:
  - Hide the Monthly Premium field
  - Show the Annual Income field and populate the input box with the amount entered
  - Show the Coverage field and populate the dropdown with 10x the amount entered for income
- If coming from `&src=calculateneed` and clicking the "I Know What I Need" button, the quote form should:
  - Hide the Annual Income field
  - Hide the Monthly Premium field
  - Show the Coverage field and populate the dropdown with $100,000
- If coming from `calculator.do`, the quote form should:
  - Hide the Annual Income field
  - Hide the Monthly Premium field
  - Show the Coverage field and populate the dropdown with the amount calculated with the needs calculator

**Comment by mohankumarac12** [comment]
Fixed. will be available in next build.
