### ISSUE TITLE
Form on new life landing path pages is broken

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#2]
Entering data and clicking GO on the three new path pages (`life-help.do`, `life-need.do`, `life-afford.do`) does not redirect to the Quote Form. It appends a string to the URL (for example, `life-afford.do?coverageAmount=50`), but the page does not advance.

**Comment by cjspurlock** [comment]
`life-need.do` and `life-afford.do` have been fixed, but `life-help.do` is still not working

**Comment by mohankumarac12** [comment]
Fixed. Will be available in next build.
