### ISSUE TITLE
Confusing spacing on multicarrier page

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#27]
Todd says:

> Spacing is confusing. “Preferred Plus” text should cling to the preferred plus coverage, instead it is closer to the standard non-smoker text. The vertical spacing should be after “Preferred Plus”, not before it.

I fixed this in the CSS and committed a new version to Mohan's GitHub.

**Comment by mohankumarac12** [comment]
Fixed. Will be available in next build
