### ISSUE TITLE
HealthIQ email change

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#29]
Donna says: 

> We shouldn't copy Todd and Scott and create process errors or potentially consumer confusion. 
Please send lead to health IQ, and blind copy me so I can track and audit Health IQ weekly with reports that I'll track on weekly leads sent to them. Thx!

Barry says:

> Mohan, in addition to returning the Health IQ email & removing Todd & Scott, we also need to bcc Donna.jermer@rgare.com. Thanks

**Comment by mohankumarac12** [comment]
Added the required email address in the properties.file. This changes will reflect once new build is pushed to production.
