### ISSUE TITLE
New styles not being called for the three old vanity URL landing pages

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#3]
I made the following changes to each file (`welcomeDropdown.jsp`, `welcomeCalculateNeed.jsp`, `welcomeTwentyFiveDollars.jsp`) to fix the issue:
- Set `xperience.css` as the main CSS file after `mylifecovered-metcon.min.css`, not `styles.css` or `nav.css`
- Changed the IDs of the `<section id="hero" class="section-photo cover">` element in each file to match the new CSS
- Got rid of `remodal.css` and `remodal-default-theme.css` because they are not being used
- Replaced an `<html>` tag with a `</div>` tag at the top of `footer.jsp`

**Mohan, if you will give me access to your GitHub at https://github.com/mohankumarac12/MyLifeCovered, I will commit my changes so you have them**

**Comment by mohankumarac12** [comment]
Hi Chris,
I have provided the access to GitHub at https://github.com/mohankumarac12/MyLifeCovered

**Comment by cjspurlock** [comment]
Thanks Mohan.

I pushed new versions of the files to GitHub at https://github.com/mohankumarac12/MyLifeCovered
