### ISSUE TITLE
Wrong coverage for $25 premium (in Affordability path)?

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#36]
Todd says:

> It gave all kinds of faulty values for a 55 year old man with the default $25. Says he could get $100,000 coverage, which is not likely true. Was same for preferred and Std non-Smkr – not likely

**Comment by mohankumarac12** [comment]
For scenarios where the difference in user selected monthly premium and EBIX returned month premium is very large(around $200). For example: for a combination of data such as DOB-1951, female smoker with selected monthly premium of 25$, EBIX returns a premium of around $200 for min. coverage of 100K. this will increase as the coverage amount increases (when the slider movement is done). We have to show the nearest premium to 25$ and 100K is near. 

As per Barry suggestion immediately force the Contact Us page so they can’t change the slider and use the language “Here's great news. You definitely have protection needs and we can help you. We cannot do this online. Please complete this form and we will be in touch shortly to assist you in getting the needed coverage”.
