### ISSUE TITLE
Multicarrier: Lincoln Life quote not updating

### ISSUE THREAD

**Issue by cjspurlock** [RGAx/mylifecovered#7]
The Lincoln Life premium isn't updating when dragging the Amount of Coverage slider; it stays stuck at $59/mo unless you drag the Number of Years to Maintain Coverage slider. Is this correct?

**Comment by mohankumarac12** [comment]
Lincoln TermAccel product will only show for term 15, 20 & 30. 
if consumer selects Term as 10 or 25in quote-form page then Lincoln will not be displayed in Quote page. if consumer selects 15 in quote-form then Lincoln will be shown in the Multi Carrier page. if again prospect slider the Term to either 10 or 25, EBIX will not return any quote for Lincoln then the quote will not update as there is no updated Premium(will show the previous premium). 
Team is working to hide the Lincoln in that scenario.
